version: '3.4'

services:
  users:
    container_name: users
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - '5000'
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:Iimpeccable1@users-db/users_prod
      - DATABASE_TEST_URL=postgres://postgres:Iimpeccable1@users-db/users_test
      - SECRET_KEY=for your eyes only
    depends_on:
      - users-db
    links:
      - users-db
  
  users-db:
    container_name: users-db
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Iimpeccable1

  nginx:
    container_name: nginx
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
