"""empty message

Revision ID: ddcaa744b571
Revises: 
Create Date: 2019-12-18 14:51:22.176890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcaa744b571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f(
        'uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f(
        'uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f(
        'uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f(
        'uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###
